### ISSUE TITLE
你好，当下拉后停顿一下，再松手，上方会出现折叠，不会展示头部，下面图片是log

### ISSUE THREAD

**Issue by dongliang0201** [oukanggui/PullLoadMoreCopyWeixinAndQQ#2]
![image](https://user-images.githubusercontent.com/8383365/62535350-c2cabc80-b87d-11e9-888a-a3a00f50cbbb.png)

**Comment by dongliang0201** [comment]
![image](https://user-images.githubusercontent.com/8383365/62535520-3371d900-b87e-11e9-8ee5-8764a4010c83.png)

**Comment by oukanggui** [comment]
你好，很感谢你的反馈，目前该问题已修复
